---
version: '3.6'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_confix:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '43000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources

networks:
  monitoring:
 
volumes:
  grafana_data:
  influxdb_data:
  influxdb_confix:
