---
version: '3.6'
services:
  influxdb:
    image: influxdb:2.5.1-alpine
    container_name: influxdb
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '43000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      
networks:
  monitoring:
 
volumes:
  grafana_data:
  influxdb_data:
